name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Install Trunk
        run: cargo install basic-http-server                            

      - name: Build with Trunk
        run: basic-http-server .


